/*
GESTOR - 7
DIRETOR - 8
CORREÇÃO - 41
ADMISSAO - 74
VALIDA KIT - 97
GERAR KIT - 89
*/

function enableFields(form) {
  log.info("INICIO do EnableFields do formulário FLUIG-0002 - ADMISSAO");

  var atividade = parseInt(getValue("WKNumState"));

  var Campos = new Array(
    // INÍCIO NOVOS CAMPOS
    { campo: "cpUpFront", atividade: "0,1,41" },
    { campo: "cpUpFrontTipo", atividade: "0,1,41" },
    { campo: "cpHiringBonus", atividade: "0,1,41" },
    { campo: "cpHiringBonusTipo", atividade: "0,1,41" },
    { campo: "cpBonusValor", atividade: "0,1,41" },
    { campo: "cpBonusTipo", atividade: "0,1,41" },
    { campo: "cpAcordoNegociacao", atividade: "0,1,41" },
    //{ campo: "cpAnexoPropostaLabel", atividade: "" }, // Sempre readonly
    // FIM NOVOS CAMPOS

    //inicio e correcao
    { campo: "txtNomeColaborador", atividade: "0,1,41" },
    { campo: "dtDataNascColaborador", atividade: "0,1,41" },
    { campo: "CORRACA", atividade: "0,1,41" },
    { campo: "NACIONALIDADECod", atividade: "0,1,41" },
    { campo: "ESTADONatalCod", atividade: "0,1,41" },
    { campo: "txtNaturalidadeCod", atividade: "0,1,41" },
    { campo: "txtSexo", atividade: "0,1,41" },
    { campo: "txtEstCivilCod", atividade: "0,1,41" },
    { campo: "GRAUINSTRUCAOCod", atividade: "0,1,41" },
    { campo: "DEFICIENTEFISICO", atividade: "0,1,41" },
    { campo: "DEFICIENTEAUDITIVO", atividade: "0,1,41" },
    { campo: "DEFICIENTEFALA", atividade: "0,1,41" },
    { campo: "DEFICIENTEVISUAL", atividade: "0,1,41" },
    { campo: "DEFICIENTEMENTAL", atividade: "0,1,41" },
    { campo: "DEFICIENTEINTELECTUAL", atividade: "0,1,41" },
    { campo: "DEFICIENTEREAB", atividade: "0,1,41" },
    { campo: "cpfcnpj", atividade: "0,1,41" },
    { campo: "TxtRg", atividade: "0,1,41" },
    { campo: "UFCARTIDENTIDADE", atividade: "0,1,41" },
    { campo: "ORGAOCARTIDENTIDADE", atividade: "0,1,41" },
    { campo: "DTEMISSAOIDENT", atividade: "0,1,41" },
    { campo: "TITULOELEITOR", atividade: "0,1,41" },
    { campo: "ZONATITELEITOR", atividade: "0,1,41" },
    { campo: "DTTITELEITOR", atividade: "0,1,41" },
    { campo: "SECAOTITELEITOR", atividade: "0,1,41" },
    { campo: "UFTITULO", atividade: "0,1,41" },
    { campo: "txtCartTrab", atividade: "0,1,41" },
    { campo: "txtSerieCart", atividade: "0,1,41" },
    { campo: "dtDataEmissaoCartTrab", atividade: "0,1,41" },
    { campo: "CODUFCTPS", atividade: "0,1,41" },
    { campo: "UFCARTTRAB", atividade: "0,1,41" },
    { campo: "NIT", atividade: "0,1,41" },
    { campo: "CARTMOTORISTA", atividade: "0,1,41" },
    { campo: "TIPOCARTHABILIT", atividade: "0,1,41" },
    { campo: "DTVENCHABILIT", atividade: "0,1,41" },
    { campo: "ORGEMISSORCNH", atividade: "0,1,41" },
    { campo: "DTEMISSAOCNH", atividade: "0,1,41" },
    { campo: "PIS", atividade: "0,1,41" },
    { campo: "BancoPIS", atividade: "0,1,41" },
    { campo: "CERTIFRESERV", atividade: "0,1,41" },
    { campo: "DtCERTIFRESERV", atividade: "0,1,41" },
    { campo: "SitMilitar", atividade: "0,1,41" },
    { campo: "NumRic", atividade: "0,1,41" },
    { campo: "OrgEmRIC", atividade: "0,1,41" },
    { campo: "DtEmRIC", atividade: "0,1,41" },
    { campo: "DtChegBras", atividade: "0,1,41" },
    { campo: "Visto", atividade: "0,1,41" },
    { campo: "RNE", atividade: "0,1,41" },
    { campo: "DTRNE", atividade: "0,1,41" },
    { campo: "OrgRNE", atividade: "0,1,41" },
    { campo: "BancoPAgto", atividade: "0,1,41" },
    { campo: "AgPagto", atividade: "0,1,41" },
    { campo: "ContPagto", atividade: "0,1,41" },
    { campo: "TipodeContPagto", atividade: "0,1,41" },
    { campo: "txtNOMETIPORUA", atividade: "0,1,41" },
    { campo: "txtRUA", atividade: "0,1,41" },
    { campo: "txtNUMERO", atividade: "0,1,41" },
    { campo: "txtCOMPLEMENTO", atividade: "0,1,41" },
    { campo: "txtCODTIPOBAIRRO", atividade: "0,1,41" },
    { campo: "txtBAIRRO", atividade: "0,1,41" },
    { campo: "txtCODETD", atividade: "0,1,41" },
    { campo: "txtCODMUNICIPIO", atividade: "0,1,41" },
    { campo: "txtCEP", atividade: "0,1,41" },
    { campo: "txtCODPAIS", atividade: "0,1,41" },
    { campo: "txtTELEFONE", atividade: "0,1,41" },
    { campo: "txtCELULAR", atividade: "0,1,41" },
    { campo: "txtTElCont", atividade: "0,1,41" },
    // ... (depois dos campos da seção Contato)
    { campo: "IDDESC_EMPRESAFILIAL", atividade: "0,1,41" },
    { campo: "descricaoJornada", atividade: "0,1,41" },
    { campo: "desc_kitAssinatura", atividade: "0,1,41" },
    { campo: "desc_kitAssinaturaValidFinal", atividade: "0,1,41" },
    { campo: "FUN_CHAPA", atividade: "0,1,41" },
    { campo: "FUN_MATRICULAESOCIAL", atividade: "0,1,41" },
    { campo: "FUN_EMAIL_CORPORATIVO", atividade: "0,1,41" },
    { campo: "FUN_ADMISSAO", atividade: "0,1,41" },
    { campo: "FUN_DATABASE", atividade: "0,1,41" },
    { campo: "FUN_TPADMISSAO_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_CCIDDESC", atividade: "0,1,41" },
    { campo: "FUN_SECAO_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_NATATIV", atividade: "0,1,41" },
    { campo: "FUN_INDADMISSAO", atividade: "0,1,41" },
    { campo: "FUN_TPREGIMEPREV", atividade: "0,1,41" },
    { campo: "FUN_HRMENSAIS", atividade: "0,1,41" },
    { campo: "FUN_HRSEMANAIS", atividade: "0,1,41" },
    { campo: "FUN_HRDIAS", atividade: "0,1,41" },
    { campo: "FUN_CATEGORIA_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_IDDESCFUN", atividade: "0,1,41" },
    { campo: "FUN_CARGO_DESC_AD", atividade: "0,1,41" },
    { campo: "selectTemRemuneracao", atividade: "0,1,41" },
    { campo: "FUN_TIPOPGTO_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_NIVELFUNCAO", atividade: "0,1,41" },
    { campo: "FUN_FAIXASALARIAL", atividade: "0,1,41" },
    { campo: "FUN_VLRSALARIO", atividade: "0,1,41" },
    { campo: "FUN_SALARIOBASE", atividade: "0,1,41" },
    { campo: "FUN_PADT", atividade: "0,1,41" },
    { campo: "FUN_CATESOCIAL_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_PGCTSIN_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_IDDESCSIND", atividade: "0,1,41" },
    { campo: "FUN_CODDESCSINDICATOFILIACAO", atividade: "0,1,41" },
    { campo: "FUN_APOSENTADO", atividade: "0,1,41" },
    { campo: "FUN_PROCMENOR", atividade: "0,1,41" },
    { campo: "FUN_INSS", atividade: "0,1,41" },
    { campo: "FUN_IRRF", atividade: "0,1,41" },
    { campo: "FUN_ALTFGTS", atividade: "0,1,41" },
    { campo: "FUN_CATSEFIP_IDDESC", atividade: "0,1,41" },
    { campo: "FUN_CODOCORRENCIA_IDDESC", atividade: "0,1,41" },
    { campo: "FUN_VINCEMPREG_IDDESC_AD", atividade: "0,1,41" },
    { campo: "FUN_CODQUIOSQUE_IDDESC", atividade: "0,1,41" },
    { campo: "FUN_AJUDACUSTO", atividade: "0,1,41" },
    { campo: "FUN_DIASUTEISMES", atividade: "0,1,41" },
    { campo: "FUN_DIASUTPROXMES", atividade: "0,1,41" },
    { campo: "FUN_INTEGRCONTABIL_IDDESC", atividade: "0,1,41" },
    { campo: "FUN_INTEGRGERENCIAL_IDDESC", atividade: "0,1,41" },
    // ... (restante dos campos, como Ckb1, cpReaberturaChamado, etc.)
    { campo: "txtCentroCusto", atividade: "0,1,41" },
    { campo: "txtUnidadeArea", atividade: "0,1,41" },
    { campo: "txtTipoFuncao", atividade: "0,1,41" },
    { campo: "txtAdmissao", atividade: "0,1,41" },
    { campo: "txtSalario", atividade: "0,1,41" },
    { campo: "BancoPAgto", atividade: "0,1,41" },
    { campo: "AgPagto", atividade: "0,1,41" },
    { campo: "ContPagto", atividade: "0,1,41" },
    { campo: "TipodeContPagto", atividade: "0,1,41" },
    { campo: "FGTSBANPagto", atividade: "0,1,41" },
    { campo: "txtSindicato", atividade: "0,1,41" },
    { campo: "TxtHorario", atividade: "0,1,41" },
    { campo: "TxtCodIndi", atividade: "0,1,41" },
    { campo: "TxtContSind", atividade: "0,1,41" },
    { campo: "TxtTPADM", atividade: "0,1,41" },
    { campo: "TxtMotADM", atividade: "0,1,41" },
    { campo: "TxtSitFGTS", atividade: "0,1,41" },
    { campo: "TxtSITRais", atividade: "0,1,41" },
    { campo: "TxtVINCRais", atividade: "0,1,41" },
    { campo: "PlanSaude", atividade: "0,1,41" },
    { campo: "DescAssist", atividade: "0,1,41" },
    { campo: "Substituicao", atividade: "0,1,41" },
    { campo: "CatPonto", atividade: "0,1,41" },
    { campo: "ContSalBrad", atividade: "0,1,41" },
    { campo: "Planodonto", atividade: "0,1,41" },
    { campo: "PlanoSaude", atividade: "0,1,41" },
    { campo: "MarcaPonto", atividade: "0,1,41" },
    { campo: "ValeTransp", atividade: "0,1,41" },
    { campo: "ValeAlim", atividade: "0,1,41" },
    { campo: "ValeRefeicao", atividade: "0,1,41" },
    { campo: "ValeRef", atividade: "0,1,41" },
    { campo: "TipoSanguineo", atividade: "0,1,41" },
    { campo: "TreinRH", atividade: "0,1,41" },
    { campo: "cpTpRecrutamento", atividade: "0,1,41" },
    { campo: "cpTpContratacao", atividade: "0,1,41" },
    { campo: "cpNecTreinamento", atividade: "0,1,41" },
    { campo: "cpJustTrein", atividade: "0,1,41" },
    { campo: "cpAtendComp", atividade: "0,1,41" },
    { campo: "cpJustComp", atividade: "0,1,41" },
    { campo: "NomeMae", atividade: "0,1,41" },
    { campo: "NomePai", atividade: "0,1,41" },
    { campo: "txtEmail", atividade: "0,1,41" },
    { campo: "AddCombust", atividade: "0,1,41" },
    { campo: "AuxMoradia", atividade: "0,1,41" },
    { campo: "AddPericulosidade", atividade: "0,1,41" },
    { campo: "gratificacao", atividade: "0,1,41" },
    { campo: "AddInsul", atividade: "0,1,41" },
    { campo: "TxtSegDesemprego", atividade: "0,1,41" },
    { campo: "txtNvHiera", atividade: "0,1,41" },
    { campo: "txtJornada", atividade: "0,1,41" },
    { campo: "txtGerRH", atividade: "0,1,41" },
    { campo: "txtDataRH", atividade: "0,1,41" },
    { campo: "TxtVlrContSind", atividade: "0,1,41" },
    { campo: "TxtDtContSind", atividade: "0,1,41" },
    { campo: "TxtChapa", atividade: "0,1,41" },
    { campo: "TxtDiretoriaRH", atividade: "0,1,41" },

    { campo: "Ckb1", atividade: "0,1,41" },
    { campo: "Ckb2", atividade: "0,1,41" },
    { campo: "Ckb3", atividade: "0,1,41" },
    { campo: "Ckb4", atividade: "0,1,41" },
    { campo: "Ckb5", atividade: "0,1,41" },
    { campo: "Ckb6", atividade: "0,1,41" },
    { campo: "Ckb7", atividade: "0,1,41" },
    { campo: "Ckb8", atividade: "0,1,41" },
    { campo: "Ckb10", atividade: "0,1,41" },
    { campo: "Ckb11", atividade: "0,1,41" },
    { campo: "Ckb12", atividade: "0,1,41" },
    { campo: "Ckb13", atividade: "0,1,41" },
    { campo: "Ckb14", atividade: "0,1,41" },
    { campo: "Ckb15", atividade: "0,1,41" },
    { campo: "Ckb16", atividade: "0,1,41" },
    { campo: "Ckb17", atividade: "0,1,41" },
    { campo: "Ckb18", atividade: "0,1,41" },
    { campo: "Ckb19", atividade: "0,1,41" },
    { campo: "Ckb20", atividade: "0,1,41" },
    { campo: "Ckb21", atividade: "0,1,41" },
    { campo: "Ckb22", atividade: "0,1,41" },
    { campo: "Ckb23", atividade: "0,1,41" },
    { campo: "Ckb24", atividade: "0,1,41" },
    { campo: "Ckb25", atividade: "0,1,41" },
    { campo: "Ckb26", atividade: "0,1,41" },
    { campo: "Ckb27", atividade: "0,1,41" },
    { campo: "Ckb28", atividade: "0,1,41" },
    { campo: "Ckb29", atividade: "0,1,41" },
    { campo: "Ckb30", atividade: "0,1,41" },
    { campo: "Ckb31", atividade: "0,1,41" },
    { campo: "Ckb32", atividade: "0,1,41" },
    { campo: "Ckb33", atividade: "0,1,41" },
    { campo: "Ckb34", atividade: "0,1,41" },
    { campo: "Ckb35", atividade: "0,1,41" },
    { campo: "Ckb36", atividade: "0,1,41" },
    { campo: "Ckb37", atividade: "0,1,41" },
    { campo: "Ckb38", atividade: "0,1,41" },
    { campo: "Ckb39", atividade: "0,1,41" },
    { campo: "Ckb40", atividade: "0,1,41" },
    //REABERTURA
    { campo: "cpReaberturaChamado", atividade: "41" },
    { campo: "cpParecerReabertura", atividade: "41" },
    //GESTOR IMEDIATO
    { campo: "cpAprovacaoGestor", atividade: "7" },
    { campo: "cpParecerAprovGestor", atividade: "7" },
    { campo: "cpRespGestor", atividade: "7" },
    //GESTOR IMEDIATO EM ATRASO
    { campo: "cpAprovacaoDiretor", atividade: "8" },
    { campo: "cpParecerAprovaDiretor", atividade: "8" },
    { campo: "cpRespDiretor", atividade: "8" },
    //VALIDAR O KIT
    { campo: "cpAprovacaoRH", atividade: "74" },
    { campo: "cpParecerAprovaRH", atividade: "74" },
    { campo: "txtChapaJaExiste", atividade: "74" },
    { campo: "cpRespRH", atividade: "74" },
    //GESTOR IMEDIATO EM ATRASO
    { campo: "cpAprovacaoKit", atividade: "97" },
    { campo: "cpParecerAprovaKit", atividade: "97" },
    { campo: "cpRespKIT", atividade: "97" },
    //analista bpo
    { campo: "cpParecerBPO", atividade: "89" }
  );

  for (var item in Campos) {
    var Campo = Campos[item],
      atividades = Campo["atividade"].split(",");

    if (atividades.indexOf(atividade.toString()) >= 0) {
      form.setEnabled(Campo["campo"], true);
    } else {
      form.setEnabled(Campo["campo"], false);
    }
  }

  log.info("Fim do EnableFields do formulário FLUIG-0002 - ADMISSAO");
}
